### ISSUE TITLE
moode_mpd_fifo.patch not found

### ISSUE THREAD

**Issue by Roughtrade** [antiprism/mpd_oled#1]
pi@moode:~/mpd_oled $ patch -d/ -p0 -N < moode_mpd_fifo.patch
-bash: moode_mpd_fifo.patch: Datei oder Verzeichnis nicht gefunden

Could you please fix this

regads Peter

**Comment by antiprism** [comment]
Hi Peter

Thanks for letting me know. I have now added this file into the repository.

Adrian.
