### ISSUE TITLE
display line overflow 

### ISSUE THREAD

**Issue by nocturneop15** [antiprism/mpd_oled#22]
Hi again, 
I just notticed that in iddle state, network icon next to IP address is overflowing - far right 1px column is rendered far left, row just below the first. 

 Everything else works normally, so this is just a small cosmetic glitch.
![IMG_20190724_221643_HHT](https://user-images.githubusercontent.com/37218318/61825692-2823b400-ae61-11e9-8fd9-a5cb17ac9457.jpg)

**Comment by supercrab** [comment]
I had this when I was using the wrong display command line parameter o 6. Try o 3

**Comment by antiprism** [comment]
Hi nocturneop15

I just checked my display with the ethernet icon and the display didn't wrap for me. Hopefully supercrab's suggestion will fix this for you.

Adrian.

**Comment by nocturneop15** [comment]
Hi,
supercrab is true! with 
`./mpd_oled -o 6 -b 10 -a 3c -g 1 -f 30`, display has 1 line overflow and 90% of time does not start automatically after unclean shutdown. I had to start program manually, screen started to flicker, then I close the program. Flickering stopped and display remained under service control working good, buth with 1 line overflow. 

Using `./mpd_oled -o 6 -b 10 -a 3c -g 1 -f 30`, everything is perfect. 

Thank you both for support!

**Comment by nocturneop15** [comment]
Mistype. By using`./mpd_oled -o 3 -b 10 -a 3c -g 1 -f 30`, everything is perfect :-)
