### ISSUE TITLE
Spectrum bars doesn't work

### ISSUE THREAD

**Issue by hueh** [antiprism/mpd_oled#26]
I want to thank you for you great work with oled screen ;)
I have one problem and I don't know how to fix this. Spectrum bars doesn't work:/ I attached photo how it looks now. Can you help me?

![IMG_20190923_175935](https://user-images.githubusercontent.com/5085125/65444551-8bfe3500-de30-11e9-928a-31f28bded066.jpg)

Edit: ok spectrum bars doen't work only with Volumio spotify plugin. With radio stations it works fine.
Any solution?

**Comment by antiprism** [comment]
Hi

It is difficult, but possible, to make the spectrum display work with Spotify on Volumio. See https://github.com/antiprism/mpd_oled/issues/4#issuecomment-423255641 (and the reast of that issue).

In your image, on the left of the spectrum area is small vertical bar. This might be the wifi signal display having wrapped, which can happen if you have not specified your display type correctly with
'mpd_oled -o'. See https://github.com/antiprism/mpd_oled/issues/22

Adrian.

**Comment by antiprism** [comment]
Closing. Re-open if the issue remains.
