### ISSUE TITLE
Runeaudio+R e4 enabling mpd_oled on boot

### ISSUE THREAD

**Issue by Ephesian** [antiprism/mpd_oled#45]
to get the mpd_oled to be enabled on power on in Runeaudio+R  rather than putting an entry for i2c-dev in /etc/modules you need to create a file in /etc/modules-load.d.  eg. i2c.conf, with the entry i2c-dev.

**Comment by antiprism** [comment]
Hi Ephesian

Thanks for the feedback. Looking at the Archlinux documentation I can see that this is the only method proposed. Do you think that this should be the only method mentioned in the mpd_oled install instructions, as it would work for all official and forum versions of RuneAudio? If this is the case, I could change that part of the instructions to read:

I created the file /etc/modules-load.d/i2c.conf and added the line ```i2c-dev```.

Adrian

**Comment by antiprism** [comment]
Closing, as no feedback.
