### ISSUE TITLE
How to show only Spectrum

### ISSUE THREAD

**Issue by alain93** [antiprism/mpd_oled#60]
Hi Adrian,
I installed mpd_oled on Moode and their I modified main.cpp and display.cpp to show only the spectrum and bits when playing. Now on Volumio, I installed it from source, it worked well.
Then I went in Home/volumio/src to edit main and dispaly files like i did in Moode, after saving, the screen it did not change, still showing the full set, spectrum, time and all icons.
After modif, I rebooted the system, not sure if there is anything else to do like in Moode.
Or is there another place were the files are?

**Comment by antiprism** [comment]
Hi Alain

After changing the source files you need to run `make` and `sudo make install-strip` again.

Adrian.

**Comment by alain93** [comment]
Perfecto,
 thanks Adrian
