### ISSUE TITLE
SSD1327 support request

### ISSUE THREAD

**Issue by SWRJEEDOM** [antiprism/mpd_oled#62]
Dear,

The library https://github.com/hallard/ArduiPi_OLED  supports SSD1327 Oled 1.5inches screen.
Can you please add it to mpd_oled ?

thks
Olivier

**Comment by antiprism** [comment]
Hi Oliver

Thank you for your suggestion. Looking at the library the only screen supported with this controller is a Seeed screen with a resolution of 96x96 pixels, and this is why it is excluded by mpd_oled, which uses a fixed layout on 128x64 screens.

I am currently in the process of converting mpd_oled to use the U8g2 library, which supports a wider range of screens. There might not be configurable layouts for a while, but if you have a screen that is 128 pixels whide then you will probably be able to display the 128x64 layour on it when this development is complete.

I will close the issue, as there is already an open issue here: https://github.com/antiprism/mpd_oled/issues/7

Adrian.
